### ISSUE TITLE
✨ [feat] Add support for on-the-fly conversion to Bijoy Keyboard format

### ISSUE THREAD

**Issue by hitblast** [hitblast/avro.py#26]
This issue mentions a new feature addition to avro.py which might become useful for a lot of Bengali typists. This feature will add support for outputting the parsed Bengali text via `parse()` in a format supported by the Bijoy Keyboard.

## Tasks:

- [x] Add basic dictionary mappings for the conversions.
- [x] Add basic support and unit tests for preliminary support of Bijoy format.
- [x] Add support for special Bengali alphabets (namely kars, halants etc.).
- [ ] (Optional) Add reversal support for the newly added format inside the `reverse()` function.

## Live Updates

https://github.com/hitblast/avro.py/compare/2024.1.1...main

**Comment by hitblast** [comment]
Note: I'll be working on this issue. However, contributions are always welcome!

**Comment by hitblast** [comment]
Update: The https://github.com/hitblast/avro.py/commit/1db1b513407f9fce17944a8c983dfa11927e7e0b commit has fulfilled the code requirement for all the three primary tasks mentioned below. Still needs some furnishing though, which I will be working on later today.
